version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    environment:
        - ROR_UID
        - APPNAME
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/opt/ror-app
    ports:
      - "3000:3000"
    depends_on:
      - db
